// Build the markdown editor into a single self-contained IIFE bundle (+ one CSS
// file) under web/static/vendor/. React, md-editor-rt and all their deps are
// inlined; fonts/icons are embedded as data URIs so the result works fully
// offline and is served like any other vendored asset. Run with: npm run build.
import * as esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const outdir = path.resolve(here, "../src/llm_wiki/web/static/vendor");

const fontLoaders = {
  ".ttf": "dataurl", ".woff": "dataurl", ".woff2": "dataurl",
  ".eot": "dataurl", ".svg": "dataurl", ".png": "dataurl", ".gif": "dataurl",
};

// 1) The markdown editor (React + md-editor-rt + highlight.js + cropper).
await esbuild.build({
  entryPoints: [path.join(here, "src/entry.jsx")],
  bundle: true,
  format: "iife",
  minify: true,
  target: ["es2020", "chrome100", "firefox100", "safari15"],
  define: { "process.env.NODE_ENV": '"production"' },
  loader: { ".js": "jsx", ".jsx": "jsx", ...fontLoaders },
  outfile: path.join(outdir, "md-editor.bundle.js"),
});

// 2) The reading-page code highlighter — the SAME highlight.js as the editor so
//    colours match exactly.
await esbuild.build({
  entryPoints: [path.join(here, "src/hljs-entry.js")],
  bundle: true,
  format: "iife",
  minify: true,
  target: ["es2020", "chrome100", "firefox100", "safari15"],
  outfile: path.join(outdir, "hljs.bundle.js"),
});

// 3) Offline Mermaid for the reading view — fenced ```mermaid blocks become SVG
//    diagrams with no CDN. Exposes window.WikiMermaid.run(root).
await esbuild.build({
  entryPoints: [path.join(here, "src/mermaid-entry.js")],
  bundle: true,
  format: "iife",
  minify: true,
  target: ["es2020", "chrome100", "firefox100", "safari15"],
  outfile: path.join(outdir, "mermaid.bundle.js"),
});

// 4) GitHub light/dark token colours, scoped to .rendered so they only touch the
//    reading view (light by default, dark under [data-theme="dark"]). Backgrounds
//    and layout are dropped — the .rendered <pre> box keeps using the app palette.
function scopeTheme(file, scope) {
  const css = fs.readFileSync(file, "utf8").replace(/\/\*[\s\S]*?\*\//g, "");
  const keep = new Set(["color", "font-weight", "font-style", "text-decoration"]);
  const rules = [];
  for (const chunk of css.split("}")) {
    const i = chunk.indexOf("{");
    if (i < 0) continue;
    const sel = chunk.slice(0, i).trim();
    const decls = chunk.slice(i + 1).split(";").map((d) => d.trim()).filter(Boolean)
      .filter((d) => keep.has(d.slice(0, d.indexOf(":")).trim()));
    if (!sel || !decls.length) continue;
    const sels = sel.split(",").map((s) => scope + " " + s.trim()).join(", ");
    rules.push(sels + " { " + decls.join("; ") + "; }");
  }
  return rules.join("\n");
}
const stylesDir = path.join(here, "node_modules/highlight.js/styles");
const themeCss = [
  "/* highlight.js GitHub token colours, scoped to .rendered (light default + [data-theme=dark]). Generated by build.mjs — do not edit. */",
  scopeTheme(path.join(stylesDir, "github.css"), ".rendered"),
  scopeTheme(path.join(stylesDir, "github-dark.css"), '[data-theme="dark"] .rendered'),
].join("\n") + "\n";
fs.writeFileSync(path.join(outdir, "hljs-theme.css"), themeCss);

console.log("built -> vendor/md-editor.bundle.{js,css}, hljs.bundle.js, hljs-theme.css, mermaid.bundle.js");
